/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class ModifyInventary extends javax.swing.JPanel {

     /**
      * Creates new form ModifyInventary
      */
     public ModifyInventary() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tablaModificacion = new javax.swing.JTable();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          botonActualiza = new javax.swing.JButton();
          botonLimpiaCampos = new javax.swing.JButton();
          jTextField1 = new javax.swing.JTextField();
          jTextField2 = new javax.swing.JTextField();
          jTextField3 = new javax.swing.JTextField();
          jTextField4 = new javax.swing.JTextField();
          jTextField5 = new javax.swing.JTextField();
          jTextField6 = new javax.swing.JTextField();
          jTextField7 = new javax.swing.JTextField();
          jTextField8 = new javax.swing.JTextField();
          jTextField9 = new javax.swing.JTextField();

          setLayout(new java.awt.BorderLayout());

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
          jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          tablaModificacion.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Id", "Descripcion", "Talla", "Marca", "Tipo de producto", "Precio", "Edad dirigida", "Cantidad", "Sexo"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tablaModificacion.getTableHeader().setReorderingAllowed(false);
          tablaModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tablaModificacionMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tablaModificacion);

          jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1220, 470));

          jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(0, 0, 0));
          jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel2.setText("Id");
          jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, -1));

          jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel3.setForeground(new java.awt.Color(0, 0, 0));
          jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel3.setText("Descripción");
          jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 100, -1));

          jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel4.setForeground(new java.awt.Color(0, 0, 0));
          jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel4.setText("Talla");
          jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 60, -1));

          jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel5.setForeground(new java.awt.Color(0, 0, 0));
          jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel5.setText("Marca");
          jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 90, -1));

          jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel6.setForeground(new java.awt.Color(0, 0, 0));
          jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel6.setText("Tipo de producto");
          jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 150, -1));

          jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel7.setForeground(new java.awt.Color(0, 0, 0));
          jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel7.setText("Precio");
          jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

          jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel8.setForeground(new java.awt.Color(0, 0, 0));
          jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel8.setText("Edad dirigida");
          jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

          jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel9.setForeground(new java.awt.Color(0, 0, 0));
          jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel9.setText("Cantidad");
          jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

          jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
          jLabel10.setForeground(new java.awt.Color(0, 0, 0));
          jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel10.setText("Sexo");
          jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

          botonActualiza.setText("Actualizar");
          botonActualiza.setFocusable(false);
          botonActualiza.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonActualizaActionPerformed(evt);
               }
          });
          jPanel1.add(botonActualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 140, 40));

          botonLimpiaCampos.setText("Limpiar campos");
          botonLimpiaCampos.setFocusable(false);
          jPanel1.add(botonLimpiaCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 140, 40));
          jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 30));
          jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));
          jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, 30));
          jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, 30));
          jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 110, 30));
          jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 160, 30));

          jTextField7.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField7ActionPerformed(evt);
               }
          });
          jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, 30));
          jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 100, 30));
          jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 100, 30));

          add(jPanel1, java.awt.BorderLayout.CENTER);
     }// </editor-fold>//GEN-END:initComponents

     private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
          
     }//GEN-LAST:event_jTextField7ActionPerformed

     private void botonActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizaActionPerformed
         
     }//GEN-LAST:event_botonActualizaActionPerformed

     private void tablaModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaModificacionMouseClicked
         
     }//GEN-LAST:event_tablaModificacionMouseClicked


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton botonActualiza;
     private javax.swing.JButton botonLimpiaCampos;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField2;
     private javax.swing.JTextField jTextField3;
     private javax.swing.JTextField jTextField4;
     private javax.swing.JTextField jTextField5;
     private javax.swing.JTextField jTextField6;
     private javax.swing.JTextField jTextField7;
     private javax.swing.JTextField jTextField8;
     private javax.swing.JTextField jTextField9;
     private javax.swing.JTable tablaModificacion;
     // End of variables declaration//GEN-END:variables
}
